### ISSUE TITLE
ねるな

### ISSUE THREAD

**Issue by haruki-takashina** [a-nitanai/hokkoriPlace-issue#6]

**Comment by takisawakodai** [comment]
にちゃないさんの睡眠欲には感無量です。
しかしながらこの先に不安を感じているのも確かです。

**Comment by haruki-takashina** [comment]
### いつも寝ていて困っています　☆★★★★(Gitユーザーのレビュー)
始めは優等生な感じがありました。ですがよく観察してみると似内さんが
毎日のように寝ているみたいなんです。
この先の開発や就職後もそうなってしまうのではないかと心配です。
なので星１つとさせていただきました。


　　　　このレビューが役に立ちましたか？　[役に立った] [役に立たなかった]

**Comment by takisawakodai** [comment]
### もうダメみたい　☆★★★★(GitHubユーザのレビュー)
高橋先生の授業では絶対に寝ないように努力？しているようですが、
他の先生の場合はからっきしです。
卒業研究も山口組でラズパイをやるということですがいつ投げ出すかわかりません。
私の上の人と同じく星1つとさせていただきます。

　　　　　このレビューが役に立ちましたか？　[役に立った] [役に立たなかった]

**Comment by RyugoHarada** [comment]
**将来が心配　☆★★★★(GitHubユーザのレビュー)**

授業中の居眠りが多すぎて就職してから心配です。
幸い彼の入社先はコアタイムなしのフレックスらしいですが彼の場合15:00出社なんてこともあり得そうです。
そもそも、１年間はフレックスを使えないのでその間に居眠りしすぎてクビになりますね。
私も同じく星１つとさせていただきます。

　　　　　　このレビューが役に立ちましたか？　[役に立った] [役に立たなかった]

**Comment by a-nitanai** [comment]
### 周りがひどすぎる　☆★★★★(Gitユーザーのレビュー)
彼自体は頑張っているようですが、周りの環境（江南高校出身など）が劣悪で少なからず影響を与えているようです。
彼に非はないですがこのような理由から星１つとさせていただきます。

　　　　このレビューが役に立ちましたか？　[役に立った] [役に立たなかった]

**Comment by RyugoHarada** [comment]
**救いようがない　☆★★★★(Gitユーザーのレビュー)**

彼は心配してくれている仲間たちに対して悪態をついて全然反省をしていません。
このままだと現在彼が進めている開発プロジェクトの中で、彼が分からない時に教えてくれるような方も居なくなってしまうのではないでしょうか。

**Comment by RyugoHarada** [comment]
> ### 周りがひどすぎる　☆★★★★(Gitユーザーのレビュー)
> 彼自体は頑張っているようですが、周りの環境（江南高校出身など）が劣悪で少なからず影響を与えているようです。
> 彼に非はないですがこのような理由から星１つとさせていただきます。
> 
> 　　　　このレビューが役に立ちましたか？　[役に立った] [役に立たなかった]

**Comment by takisawakodai** [comment]
### 福屋の癖が強すぎる　☆★★★★(Gitユーザーのレビュー)

彼女の独裁的な進め方にはかつての国家社会主義ドイツ労働者党（ナチス）の指導者であるアドルフ・ヒトラーに似たものがあります。
メンバーはとても疲弊したようすでした。彼女のもとで仕事をすることはすなわち死を意味するものです。中途半端に開発をせず逃げるなら今です。

**>全て投げ出してもいいじゃないの? Used to be 諦めるのは easy**

**Comment by RyugoHarada** [comment]
後ろにいんだよコラ

**Comment by RyugoHarada** [comment]
### 少し良くなった　☆✯★★★(Gitユーザーのレビュー)
前まではシステム設計の授業の時間はフルで寝ていましたが、今日は3時限目の時に起きていたので星1.5とさせていただきました。

　　　　このレビューが役に立ちましたか？　[役に立った] [役に立たなかった]

**Comment by haruki-takashina** [comment]
### 🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔🤔

**Comment by RyugoHarada** [comment]
### やっぱりダメだった　☆★★★★(Gitユーザーのレビュー)
起きていると思ったら顔を伏せていないだけで目が完全に閉じています。

　　　　このレビューが役に立ちましたか？　[役に立った] [役に立たなかった]

**Comment by haruki-takashina** [comment]
／￣＼
○ ／￣￣￣＼ヘ
　 /・　 ・　 ＼>
／￣￣￣＼　　 Ｖ|
｜ ――― ｜　　｜|
＼＿＿＿／　　 ∧|
　　＼　　　　／〉
　　　￣￣￣￣￣
